name: Build MacOS

on: 
  push:

  # Manual run
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    defaults:
      run:
        working-directory: ./python3-macos    
    strategy:
      matrix:
        env:
          - { ARCH: x86_64, PYVER: 3.7.9 }
          
          - { ARCH: x86_64, PYVER: 3.8.9 }
          
          - { ARCH: x86_64, PYVER: 3.9.9 }

          - { ARCH: x86_64, PYVER: 3.10.4 }
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.4'
    - name: Build Python
      run: |
        # Make the script runnable
        chmod +x build.sh

        # Set env parameters
        export ARCH=${{ matrix.env.ARCH }}
        export PYVER=${{ matrix.env.PYVER }}

        # Run the build script
        ./build.sh