name: Build MacOS

on: 
  push:

  # Manual run
  workflow_dispatch:

jobs:
  build_macos_x86_64:
    runs-on: macos-10.15
    defaults:
      run:
        working-directory: ./python3-macos    
    strategy:
      matrix:
        env:
          - { PYVER: 3.7.9 }
          
          - { PYVER: 3.8.9 }
          
          - { PYVER: 3.9.9 }

          - { PYVER: 3.10.4 }
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.4'
    - name: Build Python
      run: |
        # Make the script runnable
        chmod +x build.sh

        # Set env parameters
        export PYVER=${{ matrix.env.PYVER }}

        # Run the build script
        ./build.sh
    - name: Create package
      id: create_package
      run: |
        cd embedabble           
        package_filename=python3-macos-${{ matrix.env.PYVER }}-x86_64.zip
        7z a -t7z $package_filename * -r
        ls -R
    - name: Save build
      uses: actions/upload-artifact@v2
      with:
        path: python3-macos/embedabble/python3-macos-${{ matrix.env.PYVER }}-x86_64.zip
        if-no-files-found: error