name: Build Linux

on: 
  push:

  # Manual run
  workflow_dispatch:

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python3-linux    
    strategy:
      matrix:
        env:
          - { PYVER: 3.7.16 }
          
          - { PYVER: 3.8.16 }
          
          - { PYVER: 3.9.16 }

          - { PYVER: 3.10.9 }

          - { PYVER: 3.11.2 }
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v2
    - name: Update scripts permission
      run: |        
        find -type f -iname "*.sh" -exec chmod +x {} \;
        find ./Linux -type f -iname "*.py" -exec chmod +x {} \;
    - name: Building
      run: |
        docker run --rm -v $(pwd):/python3-linux \
            --env PYVER=${{ matrix.env.PYVER }} \
            python:${{ matrix.env.PYVER }}-slim /python3-linux/docker-build.sh        
    - name: Create package
      id: create_package
      run: |
        cd embedabble         
        package_filename=python3-linux-${{ matrix.env.PYVER }}-x86_64.zip
        sudo 7z a -tzip $package_filename * -r
        echo ::set-output name=package_filename::$package_filename
    - name: Save build
      uses: actions/upload-artifact@v2
      with:
        path: python3-linux/embedabble/${{ steps.create_package.outputs.package_filename }}
        if-no-files-found: error